name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: GetSchwifty
      fonts:
        - asset: assets/fonts/get_schwifty.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
